name: Publish Docker

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get version from the latest tag
        run: |
          git fetch --tags
          git describe --always > githash
          set /p myvar= < githash 
          echo "version=$myvar" >> $env:GITHUB_ENV
      
      - name: Build image
        run: |
          docker build . -t viralpatel9/basic-c-app:${{ env.version }}

      - name: Ensure project builds
        run: |
          docker run --rm viralpatel9/basic-c-app:${{ env.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: viralpatel9
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish image
        run: |
          docker images
          docker push viralpatel9/basic-c-app:${{ env.version }}